[ZH Percent] Added support for percentage like "[Den]分之[Num]" (#2257)
microsoft/Recognizers-Text pull request #2354
Opened 2020-11-05 13:22 UTC by LionbridgeCSII

Added support for percentage like "[Den]分之[Num]" e.g. "十分之一" (10%) in .NET and Python (#2257).
Test cases added to PercentModel.

2020-11-05 13:30 UTC, LionbridgeCSII commented
did not notice that this fix is overlapping with PR #2269, so maybe it is not needed.

2020-11-11 06:01 UTC, tellarin requested changes

2020-11-11 06:01 UTC, tellarin commented on Specs/Number/Chinese/PercentModel.json
> +          "value": "10%"
This both overlaps with PR #2269 and also only covers simple cases.

2020-11-11 06:01 UTC, tellarin commented
Closing it as #2269 seems more general.

2020-11-11 06:01 UTC, closed without merging