[SV DateTime] Swedish datetime support
microsoft/Recognizers-Text pull request #2816
Opened 2021-12-28 11:37 UTC by pete1854

Adding support for datetime in swedish

2021-12-29 09:36 UTC, tellarin commented
Hi @pete1854 I suggest making a PR just with the code skeleton for Swedish (just not registering the models) and then a PR with the translated specs. Then we go little by little by subtype refinining things.
Can you convert this PR in one for the skeleton (basically the structure copied from English with renames and some configs for Swedish)? This way we can discuss issues quickly and merge as frequently as possible.

2021-12-29 11:00 UTC, tellarin requested changes
There are only some minor issue before we can merge this skeleton.
Please change the PR from draft to regular once the changes are in. Thanks.

2021-12-29 11:01 UTC, tellarin commented on .NET/Microsoft.Recognizers.Text.DataDrivenTests/DateTime/TestDateTime_Swedish.cs
> -            ExtractorInitialize(Extractors);
I'd add this file back with these tests also commented out.

2021-12-29 11:02 UTC, pete1854 commented on .NET/Microsoft.Recognizers.Text.sln
> +# Visual Studio Version 17
Sorry, my bad. I forgot to pay attention to this. Will correct.

2021-12-29 13:39 UTC, pete1854 commented
Apart from the two indentation issues which I haven't been able to correct (since they do not exist in my code) this shouild be OK now.

2021-12-31 07:02 UTC, tellarin approved these changes
I've fixed the remaining identiation issues (tab vs whitespaces).

2021-12-31 07:04 UTC, merged