[KO Number] Korean NumberRange fixed extraction of pattern 'is 30 or at least 30'
microsoft/Recognizers-Text pull request #2851
Opened 2022-01-24 07:10 UTC by aitelint

2022-01-24 08:42 UTC, tellarin requested changes

2022-01-24 08:42 UTC, tellarin commented on Specs/Number/Korean/NumberRangeModel.json
> +        "Text": "최소 30",
Shouldn't the equals to 30 be it's own entity too?
I'm quite confused by the intended meaning of this sentenced.

2022-01-24 08:42 UTC, tellarin commented on Specs/Number/Korean/NumberRangeModel.json
> +        "Text": "최소 30",
Can you add in the PR description an explanation as detailed as possible of the interpretation and a comparison to the implemented English behaviour? Thanks.

2022-01-24 08:43 UTC, tellarin commented on Specs/Number/Korean/NumberRangeModel.json
> +        "Text": "최소 30",
If I recall correctly, cases like "equals to 30" in English have special behaviour that "is 30" doesn't.

2022-01-24 09:24 UTC, aitelint commented on Specs/Number/Korean/NumberRangeModel.json
> +        "Text": "최소 30",
yes, but according to our Korean linguist "과 같거나" here is ambiguous: 
"X 과 같거나 최소 Y" can be interpreted both as "is X or at least Y" or "is equal to X or at least Y", so we decided not to extract it.
There is another non-ambiguous case "그의 점수는 30과 같 거나 30보다 높다." (His score is equal to 30 or greater than 30) where "30과 같" is extracted.

2022-01-24 09:27 UTC, aitelint commented on Specs/Number/Korean/NumberRangeModel.json
> +        "Text": "최소 30",
But I can add also "과 같거나" to the EqualRegex, maybe it is better to extract it.

2022-01-25 02:28 UTC, tellarin commented on Specs/Number/Korean/NumberRangeModel.json
> +        "Text": "최소 30",
Can you add a comment to the spec case about "과 같거나" being ambiguous, to document the current behaviour? The rest looks good to me.

2022-01-25 04:58 UTC, aitelint commented on Specs/Number/Korean/NumberRangeModel.json
> +        "Text": "최소 30",
added

2022-01-25 05:36 UTC, tellarin approved these changes

2022-01-25 05:37 UTC, merged